FROM node:20-alpine

WORKDIR /app
# Это директория внутри контейнера, в которой будут выполняться все команды (RUN, CMD, COPY и т.д.).
COPY package*.json ./
RUN npm install

# не копируем код — он будет примонтирован томом
CMD ["npm", "run", "dev", "--", "--host"]
