FROM python:3.11-slim

WORKDIR /app
# Это директория внутри контейнера, в которой будут выполняться все команды (RUN, CMD, COPY и т.д.).
COPY requirements.txt .
RUN pip install -r requirements.txt

# не копируем код — он будет примонтирован томом
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
